travel_profile:  # This is the profile name you define
  target: dev
  outputs:
    dev:
      type: snowflake
      account: nlhjcmr-uz76807
      user: Devanshi
      password: Devanshi@3001
      role: ACCOUNTADMIN
      database: TRAVEL_DB
      warehouse: COMPUTE_WH
      schema: public
      authenticator: snowflake
      