travel_profile:  # This is the profile name you define
  target: dev
  outputs:
    dev:
      type: snowflake
      account:  <write your account_id>
      user: <write your  user>
      password: <write your password>
      role: ACCOUNTADMIN
      database: TRAVEL_DB
      warehouse: COMPUTE_WH
      schema: public
      authenticator: snowflake
      
