create or replace TABLE TRAVEL_DB.RAW.CUSTOMER_DETAILS (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE_NUMBER VARCHAR(15),
	ADDRESS VARCHAR(255),
	COUNTRY_CODE VARCHAR(10),
	SEGMENT_ID NUMBER(38,0),
	primary key (CUSTOMER_ID)
);



